### ISSUE TITLE
exo 2

### ISSUE THREAD

**Issue by webdevproformation** [DieuveilleWebH3/exercices-javascript#1]
https://github.com/DieuveilleWebH3/exercices-javascript/blob/e2560a402aebf3f26d971885ea11d20b629b8057/03/exo2.ts#L25

type UtilisateurAnonyme = (Required<Pick<Administrateur, 'ip'>> & Partial<Pick<Administrateur, 'nom'>>);

**Comment by DieuveilleWebH3** [comment]
Merci. 
Je l'ai corrigé, je n'avais pas remarqué que "nom" était optionnel.
